name: CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'release-*'
  workflow_run:
    workflows: [ build-publish ]
    types:
      - completed
jobs:
  client-lint:
    name: Client Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Run client linter
        run: |
          npm ci
          npm run lint

  deploy:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: [ build-publish ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull Docker Image from ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: bahmni-msf/primero
        run: |
          docker pull $ECR_REGISTRY/$REPOSITORY:latest