name: Build And Publish Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (Example: qa, staging, production)"
        required: true
        default: "qa"
      branch:
        description: "Branch to deploy from (default: ecs-github-workflow)"
        required: true
        default: "ecs-github-workflow"
      build:
        description: "Whether to build or not"
        required: false
        default: "true"
      deploy:
        description: "Whether to deploy or not"
        required: false
        default: "true"
      services-json:
        description: "JSON file containing service definitions"
        required: true
        default: '[ { "service_name": "application", "task_definition": "docker/environment/qa/task_definition/application.json", "container_name": "Application", "image": "", "image-name": "application", "ecr-repo": "potm/application" }, { "service_name": "nginx", "task_definition": "docker/environment/qa/task_definition/nginx.json", "container_name": "Nginx", "image": "", "image-name": "nginx", "ecr-repo": "potm/nginx" } ]'
      cluster:
        type: string
        description: "Which Cluster to deploy"
        required: false
        default: "POTMDev"

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build == 'true' }}
    environment: ${{ format('{0}_{1}', github.event.inputs.environment, github.event.inputs.cluster) }}
    strategy:
      fail-fast: false
      matrix:
        service: ${{fromJson(github.event.inputs.services-json)}}
    outputs:
      image-name-${{ env.uniqueID }}: ${{ steps.build-and-push.outputs.image-name }}
    steps:
      - name: Pull Github code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image tag variable
        run: |
          pwd
          echo $GITHUB_RUN_NUMBER
          echo "ARTIFACT_VERSION=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Generate Unique ID
        id: generate-unique-id
        run: |
          echo "uniqueID=$(date +%s)" >> $GITHUB_ENV

      - name: Build and Push Docker Image to ECR
        id: build-and-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.ARTIFACT_VERSION }}
        run: |
          # Run your docker build and push commands here
          # Store the generated image names
          IMAGE_NAMES=$(./docker/build.sh "${{ matrix.service.image-name }}" -d "${{ steps.login-ecr.outputs.registry }}" -t "${IMAGE_TAG}" -r "${{ matrix.service.ecr-repo }}")
          echo "::set-output name=image-name-${{ env.uniqueID }}::${IMAGE_NAMES}"

  update-service-json:
    if: ${{ github.event.inputs.deploy == 'true' }}
    needs: [docker-build-publish]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{fromJson(github.event.inputs.services-json)}}
    outputs:
      services-json: ${{ steps.update-services.services-json }}
    steps:
      - name: Save service JSON to file
        run: |
          echo "${{ github.event.inputs.services-json }}" > services.json

      - name: Update service definitions with image names
        id: update-services
        run: |
          # Read image names from environment variables
          IMAGE_NAMES=$(echo "${{ needs.docker-build-publish.outputs['image-name-${{ env.uniqueID }}'] }}")

          # Update the image field in the services JSON with the generated image names
          IMAGE_NAMES=$(echo "$IMAGE_NAMES" | tr -d '\n')

          # Check if image names are empty
          if [ -z "$IMAGE_NAMES" ]; then
            echo "Error: No image names were generated."
            exit 1
          fi

          # Check if services.json exists
          if [ ! -f "services.json" ]; then
            echo "Error: services.json not found."
            exit 1
          fi

          # Use jq to update the image field
          if ! updated_json=$(jq '.[].image = $image_names' --arg image_names "$IMAGE_NAMES" services.json); then
            echo "Error: Failed to update image names in services.json."
            exit 1
          fi

          # Save the updated JSON to a file
          if ! echo "$updated_json" > updated_services.json; then
            echo "Error: Failed to save updated JSON to updated_services.json."
            exit 1
          fi

          # Display the updated JSON
          cat updated_services.json

          # Set the output
          echo "::set-output name=services-json::$(<updated_services.json)"
        shell: bash

  deploy_to_ecs:
    if: ${{ github.event.inputs.deploy == 'true' }}
    needs: [update-service-json]
    strategy:
      fail-fast: false
      matrix:
        service: ${{fromJson(github.event.inputs.services-json)}}
    uses: bahmni-msf/primero/.github/workflows/deploy-ecs.yml@ecs-github-workflow
    with:
      environment: ${{ github.event.inputs.environment }}
      branch: ${{ github.event.inputs.branch }}
      cluster: ${{ github.event.inputs.cluster }}
      services-json: ${{ needs.update-service-json.outputs.services-json }}
    secrets: inherit
