# Copyright (c) 2014 - 2023 UNICEF. All rights reserved.

name: App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'release-*'
  workflow_dispatch:

jobs:
  server-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.7
        env:
          POSTGRES_DB: primero_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build/Run Solr
        run: |
          cd docker && ./build.sh solr
          docker run -v solr_cores:/var/solr primeroims/solr:latest make-primero-core.sh primero-test
          docker images
          docker run -d -p 8983:8983 -v solr_cores:/var/solr --name=primero_solr_1 primeroims/solr:latest
          docker ps
      - name: Server tests
        run: ./bin/run_server_tests.sh github-actions
        shell: bash
  # Running front-end mocha test in batches. Running on single process causes test
  # to run out of resources. This causes a few test to randomly timeout.
  client-lint:
    name: Client Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Run client linter
        run: |
          npm ci
          npm run lint

  client-test:
    name: Frontend Tests
    needs: client-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Run client tests batch 1
        run: |
          npm ci
          npm run test:batch:1
      - name: Run client tests batch 2
        run: |
          npm ci
          npm run test:batch:2
      - name: Run client tests batch 3
        run: |
          npm ci
          npm run test:batch:3
      - name: Run client tests 4
        run: |
          npm ci
          npm run test:batch:4
      - name: Run client tests 5
        run: |
          npm ci
          npm run test:batch:5
      - name: Run client tests new
        run: |
          npm ci
          npm run test:new -- --maxWorkers=2

  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    needs: [server-test, client-test]
    steps:
      - name: Pull Github code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: bahmni-msf/primero

        run: |
          docker build --build-arg APP_ROOT=/srv/primero/application --build-arg RAILS_LOG_PATH=/srv/primero/application/log/primero --build-arg APP_UID=1000 --build-arg APP_GID=1000 -t primero:latest -f  docker/application/Dockerfile .

      - name: Set Image tag variable
        run: echo "ARTIFACT_VERSION=1.0.0-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Tag and Push docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: bahmni-msf/primero
          IMAGE_TAG: ${{ env.ARTIFACT_VERSION }}
        run: |
          docker tag primero:latest $ECR_REGISTRY/$REPOSITORY:latest
          docker tag primero:latest $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$REPOSITORY:latest

    deploy-to-qa:
      name: Deploy
      runs-on: ubuntu-latest
      needs: docker-build-publish
      steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
        - name: Get IP
          id: ip
          uses: haythem/public-ip@v1.2
        - name: Add Github Actions IP to Security group
          run: |
            aws ec2 authorize-security-group-ingress --group-id ${{ secrets.BAHMNI_LITE_AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

        - name: Deploy to QA
          env:
            PRIVATE_KEY: ${{ secrets.BAHMNI_LITE_AWS_SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.BAHMNI_LITE_AWS_SSH_HOST}}
            USER_NAME: ${{secrets.BAHMNI_LITE_AWS_SSH_USER_NAME}}
            EC2_IP: ${{secrets.EC2_PRIMERO_IP}}
          run: |
            echo "$PRIVATE_KEY" > ~/private_key.pem && chmod 400 ~/private_key.pem
            ssh -i ~/private_key.pem -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
            echo "${{secrets.BAHMNI_LITE_AWS_SSH_PRIVATE_KEY}}" > ~/private_key.pem && chmod 400 ~/private_key.pem
            ssh -i ~/private_key.pem ubuntu@${{secrets.EC2_PRIMERO_IP}} "
              sudo su
              sudo aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 485402728093.dkr.ecr.ap-south-1.amazonaws.com
              cd bahmni-docker/bahmni-lite
              sudo docker compose --env-file .env.dev pull
              sudo docker compose --env-file .env.dev up -d
            "
            rm ~/private_key.pem
            '