# .github/workflows/deploy-ecs-qa.yml

name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (Example: qa, staging, production)'
        required: true
        default: 'qa'
      branch:
        description: 'Branch to deploy from (default: ecs-github-workflow)'
        required: true
        default: 'ecs-github-workflow'
      services-json:
        description: 'Which service or services to deploy in ecs'
        required: true
        default: '[{ "service_name": "application", "task_definition": "docker/environment/qa/task_definition/application.json", "container_name": "application", "image": "adsadads:87899" }, { "service_name": "nginx", "task_definition": "docker/environment/qa/task_definition/nginx.json", "container_name": "nginx", "image": "sfdsfds:678" }]'
      cluster:
        description: 'Which Cluster to deploy'
        required: true
        default: 'POTMDev'


# env:
#   ENVIRONMENT: ${{ github.event.inputs.environment }}


jobs:

  deploy:
    runs-on: ubuntu-latest

    env:
      ECS_CLUSTER: ${{ github.event.inputs.cluster }}
      SERVICES: ${{ github.event.inputs.services-json }}
      BRANCH: ${{ github.event.inputs.branch }}

    steps:
      - name: Pull Github code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configure AWS Credentials
        if: ${{ github.event.inputs.environment == 'qa' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS Credentials
        if: ${{ github.event.inputs.environment == 'staging' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS Credentials
        if: ${{ github.event.inputs.environment == 'production' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}

      # - name: Parse JSON input
      #   id: parse-json
      #   run: |
      #     services_json=$SERVICES
      #     echo "Parsed JSON: $services_json"
      #     echo "::set-output name=services::$services_json"

      - name: Print current directory
        run: pwd

      - name: Update task definition and deploy ECS service
        run: |
          chmod +x update_ecs_service.sh
          ./update_ecs_service.sh
        continue-on-error: false

